# Warframe 裂缝映射表

NORMAL_PLANETS = {
    0: "水星",
    1: "金星",
    2: "地球",
    3: "火星",
    4: "木星",
    5: "土星",
    6: "天王星",
    7: "海王星",
    8: "冥王星",
    9: "谷神星",
    10: "阋神星",
    11: "塞德娜",
    12: "欧罗巴",
    13: "氏族道场",
    14: "虚空",
    15: "火卫一",
    16: "火卫二",
    17: "月球",
    18: "赤毒要塞",
    19: "圣殿",
    20: "九重天",
    21: "扎里曼号",
    22: "双衍王境",
    23: "霍尼瓦尔",
}

STEEL_PLANETS = {
    0: "水星",
    1: "金星",
    2: "地球",
    3: "火星",
    4: "谷神星",
    5: "木星",
    6: "土星",
    7: "天王星",
    8: "海王星",
    9: "冥王星",
    10: "塞德娜",
    11: "阋神星",
    12: "虚空",
    13: "欧罗巴",
    14: "火卫二",
    15: "虚空",
    16: "火卫一",
    17: "扎里曼",
    18: "月球",
    19: "赤毒要塞",
    20: "Passage",
    21: "Duviri",
    22: "扎里曼号",
}

PLANET_NAME_FALLBACKS = {
    "Mercury": "水星",
    "Venus": "金星",
    "Earth": "地球",
    "Mars": "火星",
    "Ceres": "谷神星",
    "Jupiter": "木星",
    "Saturn": "土星",
    "Uranus": "天王星",
    "Neptune": "海王星",
    "Pluto": "冥王星",
    "Sedna": "塞德娜",
    "Eris": "阋神星",
    "Void": "虚空",
    "Europa": "欧罗巴",
    "Deimos": "火卫二",
    "Phobos": "火卫一",
    "Zariman": "扎里曼",
    "Lua": "月球",
    "Kuva Fortress": "赤毒要塞",
    "Duviri": "双衍王境",
    "PlutoHUB": "冥王星中继站",
    "Arval": "火星 - Arval",
    "Suisei": "水星 - Suisei",
    "Nuovo": "谷神星 - Nuovo",
    # "SolNode12": "水星 - Elion",
    # "SolNode15": "地球 - Pacific",
    # "SolNode20": "土星 - Telesto",
    # "SolNode24": "地球 - Oro",
    # "SolNode32": "土星 - Tethys",
    # "SolNode45": "火星 - Ara",
    # "SolNode49": "海王星 - Larissa",
    # "SolNode64": "天王星 - Umbriel",
    # "SolNode78": "海王星 - Triton",
    # "SolNode82": "土星 - Calypso",
    # "SolNode101": "金星 - Kiliken",
    # "SolNode102": "冥王星 - Oceanum",
    # "SolNode108": "水星 - Tolstoj",
    # "SolNode122": "天王星 - Stephano",
    # "SolNode125": "木星 - Io",
    # "SolNode128": "金星 - E Gate",
    # "SolNode177": "赛德娜 - Kappa",
    # "SolNode189": "赛德娜 - Naga",
    # "SolNode212": "欧罗巴 - Paimon",
    # "SolNode305": "月球 - Stofler",
    # "SolNode711": "火卫二 - Terrorem",
    # "SolNode708": "火卫二 - Phlegyas",
    # "SolNode718": "火卫二 - 异化区",
    # "SolNode748": "赤毒要塞 - Garus",
    # "SettlementNode11": "火卫一 - Gulliver",
    # "SettlementNode15": "火卫一 - Sharpless",
}

SPECIAL_NODE_MAP = {
    "CrewBattleNode": "航道飞机",
}

MISSION_TYPE_MAP = {
    # "MT_AIRSTRIKE": "空袭",
    # "MT_ALERT": "警报",
    "MT_ARTIFACT": "中断",
    "MT_ALCHEMY": "元素转换",
    # "MT_ARCHON": "执刑官",
    "MT_ASSASSINATE": "刺杀",
    "MT_ASSASSINATION": "刺杀",
    "MT_ASSAULT": "强袭",
    "MT_CAPTURE": "捕获",
    "MT_CORRUPTION": "虚空洪流",
    "MT_DEFENSE": "防御",
    # "MT_DEFECTION": "离心离德",
    "MT_EVACUATION": "叛逃",
    "MT_EXCAVATE": "挖掘",
    "MT_EXTERMINATE": "歼灭",
    "MT_EXTERMINATION": "歼灭",
    "MT_HIVE": "清巢",
    "MT_LANDSCAPE": "自由漫游",
    "MT_INTEL": "间谍",
    # "MT_INTERCEPT": "INTERCEPT拦截",
    "MT_MOBILE_DEFENSE": "移动防御",
    "MT_RESCUE": "救援",
    "MT_RETRIEVAL": "劫持",
    "MT_SABOTAGE": "破坏",
    "MT_SPY": "间谍",
    "MT_SURVIVAL": "生存",
    "MT_TERRITORY": "拦截",
    "MT_VOID_CASCADE": "虚空覆涌",
}

SORT_MODIFIER_TYPE_MAP = {
    "SORTIE_MODIFIER_ARMOR": {
        "name": "敌人护甲强化",
        "description": "此处敌人的护甲已经过强化。",
    },
    "SORTIE_MODIFIER_BOW_ONLY": {
        "name": "仅限弓箭/弩",
        "description": "此处的机械干扰装置可以使大多数武器失效。因此弓箭/弩类型的武器是你的唯一选择。",
    },
    "SORTIE_MODIFIER_CORROSIVE": {
        "name": "敌人元素强化（腐蚀）",
        "description": "敌人已获得额外的腐蚀伤害和元素抗性强化。",
    },
    "SORTIE_MODIFIER_ELECTRICITY": {
        "name": "敌人元素强化",
        "description": "敌人造成的元素伤害提升。",
    },
    "SORTIE_MODIFIER_EXIMUS": {
        "name": "卓越者大本营",
        "description": "敌人的大型卓越者部队正驻扎在此处，务必小心谨慎。",
    },
    "SORTIE_MODIFIER_EXPLOSION": {
        "name": "敌人元素强化（爆炸）",
        "description": "敌人已获得额外的爆炸伤害和元素抗性强化。",
    },
    "SORTIE_MODIFIER_FIRE": {
        "name": "敌人元素强化（火焰）",
        "description": "敌人已获得额外的火焰伤害和元素抗性强化。",
    },
    "SORTIE_MODIFIER_FREEZE": {
        "name": "敌人元素强化（冰冻）",
        "description": "敌人已获得额外的冰冻伤害和元素抗性强化。",
    },
    "SORTIE_MODIFIER_HAZARD_FIRE": {
        "name": "火灾",
        "description": "船舰上发生火灾；高温将损害生命与恢复速度。",
    },
    "SORTIE_MODIFIER_HAZARD_COLD": {
        "name": "低温灾害",
        "description": "待补充",
    },
    "SORTIE_MODIFIER_HAZARD_FOG": {
        "name": "雾",
        "description": "待补充",
    },
    "SORTIE_MODIFIER_HAZARD_ICE": {
        "name": "低温外泄",
        "description": "这艘船上的低温核心发生故障，导致极度低温，而这将会减少你的护盾量。",
    },
    "SORTIE_MODIFIER_HAZARD_MAGNETIC": {
        "name": "磁力灾害",
        "description": "待补充",
    },
    "SORTIE_MODIFIER_HAZARD_RADIATION": {
        "name": "辐射灾害",
        "description": "此处由于近期太阳风暴的强烈辐射影响，所受到的任何物理伤害都将会附上辐射效果。",
    },
    "SORTIE_MODIFIER_IMPACT": {
        "name": "敌人物理强化（冲击）",
        "description": "敌人已获得额外的冲击伤害和物理抗性强化。",
    },
    "SORTIE_MODIFIER_LOW_ENERGY": {
        "name": "能量上限减少",
        "description": "虚空的能量漩涡正流经此处，战甲的能量上限将会减半同时能量再生率也会大幅降低。",
    },
    "SORTIE_MODIFIER_MAGNETIC": {
        "name": "敌人元素强化（磁力）",
        "description": "敌人已获得额外的磁力伤害和元素抗性强化。",
    },
    "SORTIE_MODIFIER_MELEE_ONLY": {
        "name": "仅限近战",
        "description": "待补充",
    },
    "SORTIE_MODIFIER_POISON": {
        "name": "敌人元素强化（毒）",
        "description": "敌人已获得额外的毒伤害和元素抗性强化。",
    },
    "SORTIE_MODIFIER_PUNCTURE": {
        "name": "敌人物理强化（穿刺）",
        "description": "敌人已获得额外的穿刺伤害和物理抗性强化。",
    },
    "SORTIE_MODIFIER_RADIATION": {
        "name": "敌人元素强化（辐射）",
        "description": "敌人已获得额外的辐射伤害和元素抗性强化。",
    },
    "SORTIE_MODIFIER_RIFLE_ONLY": {
        "name": "仅限步枪",
        "description": "待补充",
    },
    "SORTIE_MODIFIER_SECONDARY_ONLY": {
        "name": "仅限次要武器",
        "description": "待补充",
    },
    "SORTIE_MODIFIER_SHIELDS": {
        "name": "敌人护盾强化",
        "description": "此处敌人的护盾已经过强化。",
    },
    "SORTIE_MODIFIER_SHOTGUN_ONLY": {
        "name": "仅限手枪",
        "description": "待补充",
    },
    "SORTIE_MODIFIER_SLASH": {
        "name": "敌人物理强化（切割）",
        "description": "敌人已获得额外的切割伤害和物理抗性强化。",
    },
    "SORTIE_MODIFIER_VIRAL": {
        "name": "敌人元素强化（病毒）",
        "description": "敌人已获得额外的病毒伤害和元素抗性强化。",
    },
}

TILESET_MAP = {
    "CorpusShipTileset": "CorpusShipTileset",
    "GrineerAsteroidTileset": "GrineerAsteroidTileset",
    "GrineerForestTileset": "GrineerForestTileset",
    "GrineerGalleonTileset": "GrineerGalleonTileset",
    "GrineerOceanTileset": "GrineerOceanTileset",
    "GrineerSettlementTileset": "GrineerSettlementTileset",
    "OrokinVoidTileset": "OrokinVoidTileset",
}

TIER_ORDER = {
    "VoidT1": 1,
    "VoidT2": 2,
    "VoidT3": 3,
    "VoidT4": 4,
    "VoidT5": 5,
    "VoidT6": 6,
    "VoidT7": 7,
}

TIER_MAP = {
    "VoidT1": "古纪",
    "VoidT2": "前纪",
    "VoidT3": "中纪",
    "VoidT4": "后纪",
    "VoidT5": "安魂",
    "VoidT6": "全能",
    "VoidT7": "特殊",
}

NODE_METADATA = {
    "SolNode1": {
        "name": "Galatea",
        "planet": "海王星",
        "faction": "Corpus",
        "level": "27-29",
        "hardlevel": "127-129",
        "mission": "捕获"
    },
    "SolNode2": {
        "name": "Aphrodite",
        "planet": "金星",
        "faction": "Corpus",
        "level": "11-13",
        "hardlevel": "111-113",
        "mission": "移动防御"
    },
    "SolNode4": {
        "name": "Acheron",
        "planet": "冥王星",
        "faction": "Corpus",
        "level": "41-43",
        "hardlevel": "141-143",
        "mission": "歼灭",
    },
    "SolNode6": {
        "name": "Despina",
        "planet": "海王星",
        "faction": "Corpus",
        "level": "35-37",
        "hardlevel": "135-137",
        "mission": "挖掘",
    },
    # SolNode9	Rosalind, Uranus
    "SolNode9": {
        "name": "Rosalind",
        "planet": "***",
        "faction": "***",
        "level": "**-**",
        "hardlevel": "***-***",
        "mission": "**",
    },
    "SolNode10": {
        "name": "Thebe",
        "planet": "木星",
        "faction": "Corpus",
        "level": "11-13",
        "hardlevel": "111-113",
        "mission": "破坏"
    },
    "SolNode11": {
        "name": "Tharsis",
        "planet": "火星",
        "faction": "Grineer",
        "level": "14-16",
        "hardlevel": "114-116",
        "mission": "移动防御",
    },
    "SolNode12": {
        "name": "Elion",
        "planet": "水星",
        "faction": "Grineer",
        "level": "6-8",
        "hardlevel": "106-108",
        "mission": "捕获"
    },
    "SolNode14": {
        "name": "Ultor",
        "planet": "火星",
        "faction": "Grineer",
        "level": "11-13",
        "hardlevel": "111-113",
        "mission": "拦截"
    },
    "SolNode15": {
        "name": "Pacific",
        "planet": "地球",
        "faction": "Grineer",
        "level": "9-11",
        "hardlevel": "109-111",
        "mission": "救援",
    },
    "SolNode16": {
        "name": "Augustus",
        "planet": "火星",
        "faction": "Grineer",
        "level": "14-16",
        "hardlevel": "114-116",
        "mission": "挖掘"
    },
    "SolNode17": {
        "name": "Proteus",
        "planet": "海王星",
        "faction": "Corpus",
        "level": "35-37",
        "hardlevel": "135-137",
        "mission": "防御"
    },
    "SolNode18": {
        "name": "Rhea",
        "planet": "土星",
        "faction": "Grineer",
        "level": "29-31",
        "hardlevel": "129-131",
        "mission": "拦截",
    },
    "SolNode19": {
        "name": "Enceladus",
        "planet": "土星",
        "faction": "Grineer",
        "level": "28-30",
        "hardlevel": "128-130",
        "mission": "救援"
    },
    "SolNode20": {
        "name": "Telesto",
        "planet": "土星",
        "faction": "Grineer",
        "level": "27-29",
        "hardlevel": "127-129",
        "mission": "歼灭",
    },
    "SolNode21": {
        "name": "Narcissus",
        "planet": "冥王星",
        "faction": "Corpus",
        "level": "32-36",
        "hardlevel": "132-136",
        "mission": "歼灭"
    },
    "SolNode22": {
        "name": "Tessera",
        "planet": "金星",
        "faction": "Corpus",
        "level": "10-12",
        "hardlevel": "110-112",
        "mission": "防御"
    },
    "SolNode23": {
        "name": "Cytherean",
        "planet": "金星",
        "faction": "Corpus",
        "level": "11-13",
        "hardlevel": "111-113",
        "mission": "拦截",
    },
    "SolNode24": {
        "name": "Oro",
        "planet": "地球",
        "faction": "Grineer",
        "level": "27-29",
        "hardlevel": "127-129",
        "mission": "歼灭",
    },
    "SolNode25": {
        "name": "Callisto",
        "planet": "木星",
        "faction": "Corpus",
        "level": "23-25",
        "hardlevel": "123-125",
        "mission": "拦截",
    },
    "SolNode26": {
        "name": "Lith",
        "planet": "地球",
        "faction": "Grineer",
        "level": "8-10",
        "hardlevel": "108-110",
        "mission": "防御",
    },
    "SolNode27": {
        "name": "E Prime",
        "planet": "地球",
        "faction": "Grineer",
        "level": "6-8",
        "hardlevel": "106-108",
        "mission": "歼灭",
    },
    # SolNode28	Terminus, Mercury
    "SolNode30": {
        "name": "Olympus",
        "planet": "火星",
        "faction": "Grineer",
        "level": "23-25",
        "hardlevel": "123-125",
        "mission": "中断",
    },
    "SolNode31": {
        "name": "Anthe",
        "planet": "土星",
        "faction": "Grineer",
        "level": "27-29",
        "hardlevel": "127-129",
        "mission": "救援"
    },
    "SolNode32": {
        "name": "Tethys",
        "planet": "土星",
        # "faction": "Grineer",
        # "level": "21-23",
        # "hardlevel": "121-123",
        # "mission": "救援"
    },
    # SolNode33	Ariel, Uranus
    # SolNode34	Sycorax, Uranus
    "SolNode36": {
        "name": "Martialis",
        "planet": "火星",
        "faction": "Grineer",
        "level": "15-17",
        "hardlevel": "***-***",
        "mission": "救援",
    },
    "SolNode38": {
        "name": "Minthe",
        "planet": "冥王星",
        "faction": "Corpus",
        "level": "37-39",
        "hardlevel": "137-139",
        "mission": "移动防御",
    },
    "SolNode39": {
        "name": "Everest",
        "planet": "地球",
        "faction": "Grineer",
        "level": "9-11",
        "hardlevel": "109-111",
        "mission": "挖掘",
    },
    "SolNode41": {
        "name": "Arval",
        "planet": "火星",
        "faction": "Grineer",
        "level": "14-16",
        "hardlevel": "114-116",
        "mission": "间谍",
    },
    "SolNode42": {
        "name": "Helene",
        "planet": "土星",
        "faction": "Grineer",
        "level": "29-31",
        "hardlevel": "129-131",
        "mission": "防御",
    },
    "SolNode43": {
        "name": "Cerberus",
        "planet": "冥王星",
        "faction": "Corpus",
        "level": "33-38",
        "hardlevel": "133-138",
        "mission": "拦截"
    },
    "SolNode45": {
        "name": "Ara",
        "planet": "火星",
        "faction": "Infested",
        "level": "11-13",
        "hardlevel": "111-113",
        "mission": "生存"
    },
    "SolNode46": {
        "name": "Spear",
        "planet": "火星",
        "faction": "Grineer",
        "level": "11-13",
        "hardlevel": "111-113",
        "mission": "防御"
    },
    "SolNode48": {
        "name": "Regna",
        "planet": "冥王星",
        "faction": "Corpus",
        "level": "30-34",
        "hardlevel": "130-134",
        "mission": "生存"
    },
    "SolNode49": {
        "name": "Larissa",
        "planet": "海王星",
        "faction": "Corpus",
        "level": "34-36",
        "hardlevel": "134-136",
        "mission": "移动防御",
    },
    "SolNode50": {
        "name": "Numa",
        "planet": "土星",
        "faction": "Infested",
        "level": "21-26",
        "hardlevel": "121-126",
        "mission": "生存"
    },
    "SolNode51": {
        "name": "Hades",
        "planet": "冥王星",
        "faction": "Corpus",
        "level": "35-40",
        "hardlevel": "135-140",
        "mission": "生存"
    },
    "SolNode53": {
        "name": "Themisto",
        "planet": "木星",
        "faction": "Corpus",
        "level": "15-20",
        "hardlevel": "115-120",
        "mission": "刺杀"
    },
    "SolNode56": {
        "name": "Cypress",
        "planet": "冥王星",
        "faction": "Corpus",
        "level": "41-43",
        "hardlevel": "141-143",
        "mission": "破坏",
    },
    "SolNode57": {
        "name": "Sao",
        "planet": "海王星",
        "faction": "Corpus",
        "level": "35-37",
        "hardlevel": "135-137",
        "mission": "破坏",
    },
    "SolNode58": {
        "name": "Hellas",
        "planet": "火星",
        "faction": "Grineer",
        "level": "15-17",
        "hardlevel": "115-117",
        "mission": "歼灭"
    },
    "SolNode59": {
        "name": "Eurasia",
        "planet": "地球",
        "faction": "Grineer",
        "level": "1-3",
        "hardlevel": "101-103",
        "mission": "拦截"
    },
    "SolNode60": {
        "name": "Caliban",
        "planet": "天王星",
        "faction": "Grineer",
        "level": "24-29",
        "hardlevel": "124-129",
        "mission": "歼灭"
    },
    "SolNode61": {
        "name": "Ishtar",
        "planet": "金星",
        "faction": "Corpus",
        "level": "11-13",
        "hardlevel": "111-113",
        "mission": "破坏",
    },
    "SolNode62": {
        "name": "Neso",
        "planet": "海王星",
        "faction": "Corpus",
        "level": "34-36",
        "hardlevel": "134-136",
        "mission": "歼灭",
    },
    "SolNode63": {
        "name": "Mantle",
        "planet": "地球",
        "faction": "Grineer",
        "level": "7-9",
        "hardlevel": "107-109",
        "mission": "捕获",
    },
    "SolNode64": {
        "name": "Umbriel",
        "planet": "天王星",
        "faction": "Grineer",
        "level": "32-34",
        "hardlevel": "132-134",
        "mission": "拦截",
    },
    "SolNode65": {
        "name": "Gradivus",
        "planet": "火星",
        # "faction": "Grineer",
        # "level": "11-13",
        # "hardlevel": "111-113",
        # "mission": "歼灭"
    },
    "SolNode66": {
        "name": "Unda",
        "planet": "金星",
        "faction": "Corpus",
        "level": "11-13",
        "hardlevel": "111-113",
        "mission": "间谍",
    },
    "SolNode67": {
        "name": "Dione",
        "planet": "土星",
        "faction": "Grineer",
        "level": "26-28",
        "hardlevel": "126-128",
        "mission": "间谍",
    },
    "SolNode68": {
        "name": "Vallis",
        "planet": "火星",
        "faction": "Grineer",
        "level": "16-18",
        "hardlevel": "116-118",
        "mission": "移动防御",
    },
    # SolNode69	Ophelia, Uranus
    "SolNode70": {
        "name": "Cassini",
        "planet": "土星",
        "faction": "Grineer",
        "level": "26-28",
        "hardlevel": "126-128",
        "mission": "捕获",
    },
    "SolNode72": {
        "name": "Outer Terminus",
        "planet": "冥王星",
        "faction": "Corpus",
        "level": "43-45",
        "hardlevel": "143-145",
        "mission": "防御",
    },
    "SolNode73": {
        "name": "Ananke",
        "planet": "木星",
        "faction": "并合 Corpus",
        "level": "21-23",
        "hardlevel": "121-123",
        "mission": "捕获",
    },
    "SolNode74": {
        "name": "Carme",
        "planet": "木星",
        "faction": "并合 Corpus",
        "level": "21-23",
        "hardlevel": "121-123",
        "mission": "移动防御",
    },
    "SolNode75": {
        "name": "Cervantes",
        "planet": "地球",
        "faction": "Grineer",
        "level": "9-11",
        "hardlevel": "109-111",
        "mission": "破坏",
    },
    "SolNode76": {
        "name": "Hydra",
        "planet": "冥王星",
        "faction": "Corpus",
        "level": "37-39",
        "hardlevel": "***-***",
        "mission": "捕获",
    },
    "SolNode78": {
        "name": "Triton",
        "planet": "海王星",
        "faction": "Corpus",
        "level": "33-35",
        "hardlevel": "133-135",
        "mission": "救援",
    },
    "SolNode79": {
        "name": "Cambria",
        "planet": "地球",
        "faction": "Grineer",
        "level": "9-11",
        "hardlevel": "109-111",
        "mission": "间谍",
    },
    "SolNode81": {
        "name": "Palus",
        "planet": "冥王星",
        "faction": "Corpus",
        "level": "43-45",
        "hardlevel": "143-145",
        "mission": "生存",
    },
    "SolNode82": {
        "name": "Calypso",
        "planet": "土星",
        "faction": "Grineer",
        "level": "29-31",
        "hardlevel": "129-131",
        "mission": "破坏",
    },
    # SolNode83	Cressida, Uranus
    "SolNode84": {
        "name": "Nereid",
        "planet": "海王星",
        "faction": "Corpus",
        "level": "35-37",
        "hardlevel": "135-137",
        "mission": "间谍",
    },
    "SolNode85": {
        "name": "Gaia",
        "planet": "地球",
        "faction": "Grineer",
        "level": "9-11",
        "hardlevel": "109-111",
        "mission": "拦截",
    },
    # SolNode87	Ganymede, Jupiter
    "SolNode88": {
        "name": "Adrastea",
        "planet": "木星",
        "faction": "Corpus",
        "level": "18-20",
        "hardlevel": "118-120",
        "mission": "破坏",
    },
    "SolNode89": {
        "name": "Mariana",
        "planet": "地球",
        "faction": "Grineer",
        "level": "6-8",
        "hardlevel": "106-108",
        "mission": "歼灭",
    },
    "SolNode93": {
        "name": "Keeler",
        "planet": "土星",
        "faction": "Grineer",
        "level": "28-30",
        "hardlevel": "128-130",
        "mission": "移动防御",
    },
    "SolNode94": {
        "name": "Apollodorus",
        "planet": "水星",
        # "faction": "***",
        # "level": "**-**",
        # "hardlevel": "***-***",
        # "mission": "**",
    },
    "SolNode96": {
        "name": "Titan",
        "planet": "土星",
        "faction": "Grineer",
        "level": "21-26",
        "hardlevel": "121-126",
        "mission": "生存",
    },
    "SolNode97": {
        "name": "Amalthea",
        "planet": "木星",
        "faction": "并合 Corpus",
        "level": "22-24",
        "hardlevel": "122-124",
        "mission": "间谍",
    },
    "SolNode99": {
        "name": "War",
        "planet": "火星",
        "faction": "Grineer",
        "level": "11-13",
        "hardlevel": "111-113",
        "mission": "刺杀",
    },
    "SolNode100": {
        "name": "Elara",
        "planet": "木星",
        "faction": "并合 Corpus",
        "level": "23-25",
        "hardlevel": "123-125",
        "mission": "生存",
    },
    "SolNode101": {
        "name": "Kiliken",
        "planet": "金星",
        "faction": "Corpus",
        "level": "10-12",
        "hardlevel": "110-112",
        "mission": "挖掘",
    },
    "SolNode102": {
        "name": "Oceanum",
        "planet": "冥王星",
        "faction": "Corpus",
        "level": "41-43",
        "hardlevel": "141-143",
        "mission": "防御",
    },
    "SolNode103": {
        "name": "M Prime",
        "planet": "水星",
        # "faction": "***",
        # "level": "**-**",
        # "hardlevel": "***-***",
        # "mission": "**",
    },
    "SolNode104": {
        "name": "Fossa",
        "planet": "金星",
        "faction": "Corpus",
        # "level": "**-**",
        # "hardlevel": "***-***",
        # "mission": "**",
    },
    "SolNode106": {
        "name": "Alator",
        "planet": "火星",
        "faction": "Grineer",
        "level": "16-18",
        "hardlevel": "116-118",
        "mission": "拦截",
    },
    "SolNode107": {
        "name": "Venera",
        "planet": "金星",
        "faction": "Corpus",
        "level": "10-12",
        "hardlevel": "110-112",
        "mission": "捕获",
    },
    "SolNode108": {
        "name": "Tolstoj",
        "planet": "水星",
        "faction": "***",
        "level": "**-**",
        "hardlevel": "***-***",
        "mission": "刺杀",
    },
    "SolNode109": {
        "name": "Linea",
        "planet": "金星",
        "faction": "Corpus",
        "level": "10-12",
        "hardlevel": "110-112",
        "mission": "救援",
    },
    "SolNode113": {
        "name": "Ares",
        "planet": "火星",
        "faction": "Grineer",
        "level": "13-15",
        "hardlevel": "113-115",
        "mission": "破坏",
    },
    "SolNode118": {
        "name": "Laomedeia",
        "planet": "海王星",
        "faction": "Corpus",
        "level": "33-35",
        "hardlevel": "133-135",
        "mission": "中断",
    },
    "SolNode119": {
        "name": "Caloris",
        "planet": "水星",
        # "faction": "***",
        # "level": "**-**",
        # "hardlevel": "***-***",
        # "mission": "**",
    },
    "SolNode121": {
        "name": "Carpo",
        "planet": "木星",
        "faction": "并合 Corpus",
        "level": "22-24",
        "hardlevel": "122-124",
        "mission": "歼灭",
    },
    "SolNode122": {
        "name": "Stephano",
        "planet": "天王星",
        "faction": "Grineer",
        "level": "32-34",
        "hardlevel": "132-134",
        "mission": "防御",
    },
    "SolNode123": {
        "name": "V Prime",
        "planet": "金星",
        "faction": "Corpus",
        "level": "11-13",
        "hardlevel": "111-113",
        "mission": "生存",
    },
    "SolNode125": {
        "name": "Io",
        "planet": "木星",
        "faction": "并合 Corpus",
        "level": "23-25",
        "hardlevel": "123-125",
        "mission": "防御",
        "syndicate_level": 3,
        "syndicate_mission": "救援",
        "syndicate_reputation": 3680,
    },
    "SolNode126": {
        "name": "Metis",
        "planet": "木星",
        "faction": "并合 Corpus",
        "level": "20-22",
        "hardlevel": "120-122",
        "mission": "救援",
    },
    "SolNode127": {
        "name": "Psamathe",
        "planet": "海王星",
        # "faction": "Corpus",
        # "level": "**-**",
        # "hardlevel": "***-***",
        # "mission": "中断",
    },
    "SolNode128": {
        "name": "E Gate",
        "planet": "金星",
        "faction": "Corpus",
        "level": "8-10",
        "hardlevel": "108-110",
        "mission": "歼灭",
    },
    "SolNode129": {
        "name": "Orb Vallis",
        "planet": "金星",
        # "faction": "Corpus",
        # "level": "8-10",
        # "hardlevel": "108-110",
        # "mission": "**",
    },
    # SolNode130	Lares, Mercury
    "SolNode130": {
        "name": "Lares",
        "planet": "水星",
        # "faction": "Corpus",
        # "level": "**-**",
        # "hardlevel": "***-***",
        # "mission": "**",
    },
    "SolNode131": {
        "name": "Pallas",
        "planet": "谷神星",
        "faction": "Grineer",
        "level": "17-19",
        "hardlevel": "117-119",
        "mission": "歼灭",
    },
    "SolNode132": {
        "name": "Bode",
        "planet": "谷神星",
        "faction": "Grineer",
        "level": "17-19",
        "hardlevel": "117-119",
        "mission": "间谍",
    },
    "SolNode135": {
        "name": "Thon",
        "planet": "谷神星",
        "faction": "Grineer",
        "level": "20-22",
        "hardlevel": "***-***",
        "mission": "破坏",
    },
    "SolNode137": {
        "name": "Nuovo",
        "planet": "谷神星",
        "faction": "Grineer",
        "level": "18-20",
        "hardlevel": "***-***",
        "mission": "救援",
    },
    "SolNode138": {
        "name": "Ludi",
        "planet": "谷神星",
        "faction": "Grineer",
        # "level": "18-20",
        # "hardlevel": "***-***",
        # "mission": "救援",
    },
    "SolNode139": {
        "name": "Lex",
        "planet": "谷神星",
        "faction": "Grineer",
        # "level": "18-20",
        # "hardlevel": "***-***",
        # "mission": "救援",
    },
    "SolNode140": {
        "name": "Kiste",
        "planet": "谷神星",
        "faction": "Gineer",
        "level": "18-20",
        "hardlevel": "118-120",
        "mission": "移动防御",
    },
    "SolNode141": {
        "name": "Ker",
        "planet": "谷神星",
        "faction": "Grineer",
        "level": "19-21",
        "hardlevel": "119-121",
        "mission": "破坏",
    },
    "SolNode144": {
        "name": "Exta",
        "planet": "谷神星",
        "faction": "Grineer",
        # "level": "**-**",
        # "hardlevel": "***-***",
        # "mission": "生存",
    },
    "SolNode146": {
        "name": "Draco",
        "planet": "谷神星",
        "faction": "Grineer",
        "level": "20-22",
        "hardlevel": "120-122",
        "mission": "生存",
    },
    "SolNode147": {
        "name": "Cinxia",
        "planet": "谷神星",
        "faction": "Grineer",
        "level": "20-22",
        "hardlevel": "***-***",
        "mission": "拦截",
    },
    "SolNode149": {
        "name": "Casta",
        "planet": "谷神星",
        "faction": "Grineer",
        "level": "20-22",
        "hardlevel": "120-122",
        "mission": "防御",
    },
    "SolNode153": {
        "name": "Brugia",
        "planet": "阋神星",
        "faction": "Infestation",
        "level": "39-41",
        "hardlevel": "139-141",
        "mission": "救援",
    },
    "SolNode162": {
        "name": "Isos",
        "planet": "阋神星",
        "faction": "Infestation",
        "level": "39-41",
        "hardlevel": "139-141",
        "mission": "捕获",
    },
    "SolNode164": {
        "name": "Kala-azar",
        "planet": "阋神星",
        "faction": "Infestation",
        "level": "43-45",
        "hardlevel": "143-145",
        "mission": "防御",
    },
    "SolNode167": {
        "name": "Oestrus",
        "planet": "阋神星",
        "faction": "Infestation",
        # "level": "43-45",
        # "hardlevel": "143-145",
        # "mission": "防御",
        "syndicate_level": 3,
        "syndicate_mission": "歼灭",
        "syndicate_reputation": 3460,
    },
    "SolNode166": {
        "name": "Nimus",
        "planet": "阋神星",
        "faction": "Infestation",
        "level": "43-45",
        "hardlevel": "143-145",
        "mission": "生存",
    },
    "SolNode171": {
        "name": "Saxis",
        "planet": "阋神星",
        "faction": "Infestation",
        "level": "41-43",
        "hardlevel": "141-143",
        "mission": "歼灭",
    },
    "SolNode172": {
        "name": "Xini",
        "planet": "阋神星",
        "faction": "Infestation",
        "level": "43-45",
        "hardlevel": "143-145",
        "mission": "拦截",
    },
    "SolNode173": {
        "name": "Solium",
        "planet": "阋神星",
        "faction": "Infestation",
        "level": "41-43",
        "hardlevel": "141-143",
        "mission": "移动防御",
    },
    "SolNode175": {
        "name": "Naeglar",
        "planet": "阋神星",
        "faction": "Infestation",
        "level": "37-39",
        "hardlevel": "137-139",
        "mission": "清巢",
    },
    "SolNode177": {
        "name": "Kappa",
        "planet": "赛德娜",
        "faction": "Grineer",
        "level": "41-43",
        "hardlevel": "141-143",
        "mission": "中断",
    },
    "SolNode181": {
        "name": "Adaro",
        "planet": "赛德娜",
        "faction": "Grineer",
        "level": "39-41",
        "hardlevel": "139-141",
        "mission": "歼灭",
    },
    # SolNode183	Vodyanoi, Sedna
    "SolNode184": {
        "name": "Rusalka",
        "planet": "赛德娜",
        "faction": "Grineer",
        "level": "43-45",
        "hardlevel": "143-145",
        "mission": "破坏",
    },
    "SolNode185": {
        "name": "Berehynia",
        "planet": "赛德娜",
        "faction": "Grineer",
        "level": "43-45",
        "hardlevel": "143-145",
        "mission": "拦截",
    },
    "SolNode187": {
        "name": "Selkie",
        "planet": "赛德娜",
        "faction": "Grineer",
        "level": "43-45",
        "hardlevel": "143-145",
        "mission": "生存",
    },
    "SolNode188": {
        "name": "Kelpie",
        "planet": "赛德娜",
        "faction": "Grineer",
        "level": "43-45",
        "hardlevel": "***-***",
        "mission": "间谍",
    },
    "SolNode189": {
        "name": "Naga",
        "planet": "赛德娜",
        "faction": "Grineer",
        "level": "37-39",
        "hardlevel": "137-139",
        "mission": "救援",
    },
    "SolNode191": {
        "name": "Marid",
        "planet": "赛德娜",
        "faction": "Grineer",
        "level": "37-39",
        "hardlevel": "137-139",
        "mission": "救援",
    },
    "SolNode195": {
        "name": "Hydron",
        "planet": "赛德娜",
        "faction": "Grineer",
        "level": "43-45",
        "hardlevel": "143-145",
        "mission": "防御",
    },
    "SolNode196": {
        "name": "Charybdis",
        "planet": "赛德娜",
        "faction": "Ginneer",
        "level": "41-43",
        "hardlevel": "141-143",
        "mission": "移动防御",
    },
    "SolNode199": {
        "name": "Yam",
        "planet": "赛德娜",
        "faction": "Ginneer",
        # "level": "41-43",
        # "hardlevel": "141-143",
        # "mission": "移动防御",
    },
    "SolNode203": {
        "name": "Abaddon",
        "planet": "欧罗巴",
        "faction": "Corpus",
        "level": "26-28",
        "hardlevel": "126-128",
        "mission": "捕获",
    },
    "SolNode204": {
        "name": "Armaros",
        "planet": "欧罗巴",
        "faction": "Infestation",
        "level": "23-25",
        "hardlevel": "123-125",
        "mission": "多方交战 歼灭",
    },
    "SolNode205": {
        "name": "Baal",
        "planet": "欧罗巴",
        "faction": "Corpus",
        "level": "26-28",
        "hardlevel": "126-128",
        "mission": "歼灭",
    },
    "SolNode209": {
        "name": "Morax",
        "planet": "欧罗巴",
        "faction": "Corpus",
        "level": "23-25",
        "hardlevel": "123-125",
        "mission": "移动防御",
    },
    "SolNode210": {
        "name": "Naamah",
        "planet": "欧罗巴",
        "faction": "Corpus",
        "level": "21-23",
        "hardlevel": "121-123",
        "mission": "劫持",
    },
    "SolNode211": {
        "name": "Ose",
        "planet": "欧罗巴",
        "faction": "Corpus",
        "level": "26-28",
        "hardlevel": "126-128",
        "mission": "拦截",
    },
    "SolNode212": {
        "name": "Paimon",
        "planet": "欧罗巴",
        "faction": "Corpus",
        "level": "26-28",
        "hardlevel": "126-128",
        "mission": "防御",
    },
    "SolNode214": {
        "name": "Sorath",
        "planet": "欧罗巴",
        "faction": "Corpus",
        "level": "19-21",
        "hardlevel": "119-121",
        "mission": "劫持",
    },
    "SolNode215": {
        "name": "Valac",
        "planet": "欧罗巴",
        "faction": "Infestation",
        "level": "23-25",
        "hardlevel": "123-125",
        "mission": "多方交战 间谍",
    },
    "SolNode216": {
        "name": "Valefor",
        "planet": "欧罗巴",
        "faction": "Corpus",
        "level": "26-28",
        "hardlevel": "126-128",
        "mission": "挖掘",
    },
    "SolNode217": {
        "name": "Orias",
        "planet": "欧罗巴",
        "faction": "Corpus",
        "level": "25-27",
        "hardlevel": "125-127",
        "mission": "救援",
    },
    "SolNode220": {
        "name": "Kokabiel",
        "planet": "欧罗巴",
        "faction": "Corpus",
        "level": "25-27",
        "hardlevel": "125-127",
        "mission": "破坏",
    },
    "SolNode223": {
        "name": "Boethius",
        "planet": "水星",
        # "faction": "Corpus",
        # "level": "**-**",
        # "hardlevel": "***-***",
        # "mission": "**",
    },
    "SolNode224": {
        "name": "Odin",
        "planet": "水星",
        # "faction": "Corpus",
        # "level": "**-**",
        # "hardlevel": "***-***",
        # "mission": "**",
    },
    "SolNode225": {
        "name": "Suisei",
        "planet": "水星",
        # "faction": "Corpus",
        # "level": "**-**",
        # "hardlevel": "***-***",
        # "mission": "**",
    },
    "SolNode226": {
        "name": "Pantheon",
        "planet": "水星",
        # "faction": "Corpus",
        # "level": "**-**",
        # "hardlevel": "***-***",
        # "mission": "**",
    },
    "SolNode228": {
        "name": "夜灵平野",
        "planet": "地球",
        # "faction": "Corpus",
        # "level": "**-**",
        # "hardlevel": "***-***",
        # "mission": "**",
    },
    # SolNode229	Cambion Drift, Deimos
    "SolNode230": {
        "name": "永视弧域",
        "planet": "扎里曼号",
        "faction": "赤毒 Grineer",
        "level": "58-60",
        "hardlevel": "158-160",
        "mission": "虚空洪流",
    },
    "SolNode231": {
        "name": "Halako Perimeter",
        "planet": "扎里曼号",
        "faction": "赤毒 Grineer",
        "level": "58-60",
        "hardlevel": "158-160",
        "mission": "歼灭",
    },
    "SolNode232": {
        "name": "涂沃主厅",
        "planet": "扎里曼号",
        "faction": "赤毒 Grineer",
        "level": "58-60",
        "hardlevel": "158-160",
        "mission": "虚空覆涌",
    },
    "SolNode233": {
        "name": "Oro Works",
        "planet": "扎里曼号",
        "faction": "赤毒 Grineer",
        "level": "58-60",
        "hardlevel": "158-160",
        "mission": "虚空xx",
    },
    # SolNode234 居住舱
    "SolNode235": {
        "name": "翠径",
        "planet": "扎里曼号",
        "faction": "赤毒 Grineer",
        "level": "58-60",
        "hardlevel": "158-160",
        "mission": "移动防御",
    },
    "SolNode300": {
        "name": "Plato",
        "planet": "月球",
        "faction": "奥罗金",
        "level": "**-**",
        "hardlevel": "***-***",
        "mission": "移动防御",
    },
    "SolNode301": {
        "name": "Grimaldi",
        "planet": "月球",
        "faction": "奥罗金",
        # "level": "**-**",
        # "hardlevel": "***-***",
        # "mission": "移动防御",
    },
    "SolNode302": {
        "name": "Tycho",
        "planet": "月球",
        "faction": "奥罗金",
        "level": "**-**",
        "hardlevel": "***-***",
        # "mission": "移动防御",
    },
    "SolNode305": {
        "name": "Stofler",
        "planet": "月球",
        "faction": "奥罗金",
        "level": "**-**",
        "hardlevel": "***-***",
        "mission": "歼灭",
    },
    "SolNode309": {
        "name": "Yuvarium",
        "planet": "月球",
        "faction": "奥罗金",
        "level": "33-35",
        "hardlevel": "133-135",
        "mission": "联结生存",
    },
    "SolNode310": {
        "name": "Circulus",
        "planet": "月球",
        "faction": "奥罗金",
        "level": "103-105",
        "hardlevel": "203-205",
        "mission": "联结生存",
    },
    "SolNode400": {
        "name": "神王塔",
        "planet": "虚空",
        "faction": "奥罗金",
        "level": "18-20",
        "hardlevel": "140-150",
        "mission": "歼灭",
    },
    "SolNode401": {
        "name": "神后塔",
        "planet": "虚空",
        "faction": "奥罗金",
        "level": "18-20",
        "hardlevel": "118-120",
        "mission": "捕获",
    },
    "SolNode402": {
        "name": "Taranis",
        "planet": "虚空",
        "faction": "奥罗金",
        # "level": "18-20",
        # "hardlevel": "118-120",
        # "mission": "捕获",
    },
    "SolNode403": {
        "name": "法神塔",
        "planet": "虚空",
        "faction": "奥罗金",
        # "level": "40-50",
        "hardlevel": "128-130",
        "mission": "移动防御",
    },
    "SolNode404": {
        "name": "风王塔",
        "planet": "虚空",
        "faction": "奥罗金",
        "level": "28-30",
        "hardlevel": "128-130",
        "mission": "破坏",
    },
    "SolNode405": {
        "name": "阿尼塔",
        "planet": "虚空",
        "faction": "奥罗金",
        "level": "28-30",
        "hardlevel": "128-130",
        "mission": "生存",
    },
    "SolNode406": {
        "name": "乌戈塔",
        "planet": "虚空",
        "faction": "奥罗金",
        "level": "30-40",
        "hardlevel": "130-140",
        "mission": "捕获",
    },
    "SolNode407": {
        "name": "母神塔",
        "planet": "虚空",
        "faction": "奥罗金",
        "level": "30-40",
        "hardlevel": "130-140",
        "mission": "歼灭",
    },
    "SolNode408": {
        "name": "光神塔",
        "planet": "虚空",
        "faction": "奥罗金",
        "level": "40-50",
        "hardlevel": "140-150",
        "mission": "防御",
    },
    "SolNode409": {
        "name": "死灵塔",
        "planet": "虚空",
        "faction": "奥罗金",
        "level": "30-40",
        "hardlevel": "130-140",
        "mission": "生存",
    },
    "SolNode410": {
        "name": "太阳塔",
        "planet": "虚空",
        "faction": "奥罗金",
        "level": "30-40",
        "hardlevel": "***-***",
        "mission": "移动防御",
    },
    # SolNode411	Marduk, Void
    "SolNode412": {
        "name": "光理塔",
        "planet": "虚空",
        "faction": "奥罗金",
        "level": "30-40",
        "hardlevel": "130-140",
        "mission": "拦截",
    },
    # SolNode701	Jordas Golem Assassinate
    # SolNode705	Mutalist Alad V Assassinate
    "SolNode706": {
        "name": "Horend",
        "planet": "火卫二",
        # "faction": "Infestation",
        # "level": "**-**",
        # "hardlevel": "***-***",
        # "mission": "**",
    },
    "SolNode707": {
        "name": "Oro",
        "planet": "火卫二",
        "faction": "***",
        "level": "**-**",
        "hardlevel": "***-***",
        "mission": "**",
    },
    "SolNode708": {
        "name": "Phlegyas",
        "planet": "火卫二",
        # "faction": "Infestation",
        # "level": "**-**",
        # "hardlevel": "***-***",
        # "mission": "**",
    },
    "SolNode709": {
        "name": "Dirus",
        "planet": "火卫二",
        # "faction": "***",
        # "level": "**-**",
        # "hardlevel": "***-***",
        # "mission": "歼灭",
    },
    "SolNode710": {
        "name": "Formido",
        "planet": "火卫二",
        # "faction": "***",
        # "level": "**-**",
        # "hardlevel": "***-***",
        # "mission": "歼灭",
    },
    "SolNode711": {
        "name": "Terrorem",
        "planet": "火卫二",
        "faction": "***",
        "level": "**-**",
        "hardlevel": "***-***",
        "mission": "歼灭",
    },
    # SolNode712	Magnacidium, Deimos
    # SolNode713	Exequias, Deimos
    "SolNode715": {
        "name": "Effervo",
        "planet": "火卫二",
        "faction": "低语者",
        "level": "63-65",
        "hardlevel": "163-165",
        "mission": "刺杀",
    },
    "SolNode716": {
        "name": "孽杀",
        "planet": "火卫二",
        "faction": "低语者",
        "level": "63-65",
        "hardlevel": "163-165",
        "mission": "歼灭",
    },
    "SolNode717": {
        "name": "不灭之地",
        "planet": "火卫二",
        "faction": "低语者",
        "level": "63-65",
        "hardlevel": "163-165",
        "mission": "生存",
    },
    "SolNode718": {
        "name": "异化区",
        "planet": "火卫二",
        "faction": "低语者",
        "level": "63-65",
        "hardlevel": "163-165",
        "mission": "元素转换",
    },
    "SolNode719": {
        "name": "墓垒",
        "planet": "火卫二",
        "faction": "低语者",
        "level": "63-65",
        "hardlevel": "163-165",
        "mission": "镜像防御",
    },
    "SolNode720": {
        "name": "Testudo",
        "planet": "火卫二",
        "faction": "低语者",
        "level": "63-65",
        "hardlevel": "163-165",
        "mission": "Netracells",
    },
    "SolNode721": {
        "name": "卫城区",
        "planet": "火卫二",
        "faction": "低语者",
        "level": "63-65",
        "hardlevel": "163-165",
        "mission": "中断",
    },
    "SolNode741": {
        "name": "Koro",
        "planet": "赤毒要塞",
        "faction": "赤毒 Grineer",
        "level": "60-70",
        "hardlevel": "160-170",
        "mission": "强袭",
    },
    "SolNode742": {
        "name": "Nabuk",
        "planet": "赤毒要塞",
        "faction": "赤毒 Grineer",
        "level": "60-70",
        "hardlevel": "160-170",
        "mission": "防御",
    },
    "SolNode743": {
        "name": "Rotuma",
        "planet": "赤毒要塞",
        "faction": "赤毒 Grineer",
        "level": "60-70",
        "hardlevel": "160-170",
        "mission": "移动防御",
    },
    "SolNode744": {
        "name": "Taveuni",
        "planet": "赤毒要塞",
        "faction": "赤毒 Grineer",
        "level": "60-70",
        "hardlevel": "160-170",
        "mission": "赤毒生存",
    },
    "SolNode745": {
        "name": "Tamu",
        "planet": "赤毒要塞",
        "faction": "赤毒 Grineer",
        "level": "60-70",
        "hardlevel": "160-170",
        "mission": "中断",
    },
    "SolNode746": {
        "name": "Dakata",
        "planet": "赤毒要塞",
        "faction": "赤毒 Grineer",
        "level": "60-70",
        "hardlevel": "160-170",
        "mission": "歼灭",
    },
    "SolNode747": {
        "name": "Pago",
        "planet": "赤毒要塞",
        "faction": "赤毒 Grineer",
        "level": "60-70",
        "hardlevel": "160-170",
        "mission": "间谍",
    },
    "SolNode748": {
        "name": "Garus",
        "planet": "赤毒要塞",
        "faction": "赤毒 Grineer",
        "level": "60-70",
        "hardlevel": "160-170",
        "mission": "救援",
    },
    "SettlementNode1": {
        "name": "Roche",
        "planet": "火卫一",
        "faction": "Corpus",
        "level": "15-17",
        "hardlevel": "115-117",
        "mission": "歼灭",
    },
    "SettlementNode2": {
        "name": "Skyresh",
        "planet": "火卫一",
        "faction": "Corpus",
        "level": "15-17",
        "hardlevel": "115-117",
        "mission": "捕获",
    },
    "SettlementNode3": {
        "name": "Stickney",
        "planet": "火卫一",
        "faction": "Corpus",
        "level": "18-20",
        "hardlevel": "118-120",
        "mission": "生存",
    },
    "SettlementNode11": {
        "name": "Gulliver",
        "planet": "火卫一",
        "faction": "Corpus",
        "level": "18-20",
        "hardlevel": "118-120",
        "mission": "防御",
    },
    "SettlementNode12": {
        "name": "Monolith",
        "planet": "火卫一",
        "faction": "Corpus",
        "level": "18-20",
        "hardlevel": "118-120",
        "mission": "救援",
    },
    "SettlementNode14": {
        "name": "Shklovsky",
        "planet": "火卫一",
        "faction": "Corpus",
        "level": "16-18",
        "hardlevel": "116-118",
        "mission": "间谍",
        "syndicate_level": 4,
        "syndicate_mission": "拦截",
        "syndicate_reputation": 5270,
    },
    "SettlementNode15": {
        "name": "Sharpless",
        "planet": "火卫一",
        "faction": "Corpus",
        "level": "16-18",
        "hardlevel": "116-118",
        "mission": "移动防御",
    },
    "SettlementNode20": {
        "name": "Iliad",
        "planet": "火卫一",
        "faction": "Corpus",
        "level": "**-**",
        "hardlevel": "***-***",
        "mission": "刺杀",
    },
}


ITEM_NAME_MAP = {
    "OrokinReactorBlueprint": "Orokin 反应堆蓝图",
    "OrokinCatalystBlueprint": "Orokin 催化剂蓝图",
    "FormaBlueprint": "Forma 蓝图",
    "ExilusAdapterBlueprint": "特殊功能槽连接器蓝图",
    "WeaponAdapterBlueprint": "武器特殊功能槽连接器蓝图",
    "ChemComponent": "爆燃喷射器",
    "EnergyComponent": "电磁力场装置",
    "BioComponent": "突变原聚合物",
    "InfestedAladCoordinate": "异融 Alad V 导航坐标",
    "MutalistAladCoordinate": "异融 Alad V 导航坐标",
    "Fieldron": "电磁力场装置",
    "DetoniteInjector": "爆燃喷射器",
    "MutagenMass": "突变原聚合物",
    # 入侵武器部件奖励
    "DeraVandalBarrel": "德拉·破坏者 枪管",
    "DeraVandalBlueprint": "德拉·破坏者 蓝图",
    "DeraVandalReceiver": "德拉·破坏者 枪机",
    "DeraVandalStock": "德拉·破坏者 枪托",
    "GrineerCombatKnifeSortieBlueprint": "希芙 蓝图",
    "GrineerCombatKnifeHeatsink": "希芙 散热片",
    "KarakWraithBarrel": "卡拉克·亡魂 枪管",
    "LatronWraithStock": "拉特昂·亡魂 枪托",
    "SnipetronVandalBlueprint": "狙击特昂·破坏者 蓝图",
    "SnipetronVandalReceiver": "狙击特昂·破坏者 枪机",
    "StrunWraithStock": "斯特朗·亡魂 枪托",
    "TwinVipersWraithLink": "双子蝰蛇·亡魂 连接器",

    # ========== Baro 虚空商人商品 ==========
    "BaroTreasureBox": "虚空遗物",
    # ========== Mod ==========
    "FireEventMeleeMod": "爆裂刀刃",
    "SecondaryExplosionRadiusModExpert": "猛烈爆发 Prime",
    "WeaponDamageAmountModExpert": "抵近射击 Prime",
    "WeaponElectricityDamageModExpert": "充电弹头 Prime",
    "WeaponEventSlashDamageMod": "致残枪弹",
    "WeaponGlaiveOnKillBuffSecondary": "连击狂怒",
    "WeaponImpactDamageModExpert": "重创 Prime",
    # ========== 武器 ==========
    "ConclaveLeverPistol": "席尔火枪",
    "GrnOrokinRifleWeapon": "骨葬 Prime",
    "PrismaAngstrum": "棱晶•安格斯壮",
    "VTDetron": "苦痛•德特昂",
    # ========== 外观 ==========
    "BaroEphemeraB": "Ki'teer 尊崇幻纹",
    "EarpieceBaroB": "Ki'teer 单个耳饰",
    "EarpieceBaroC": "Ki'teer 大气耳饰",
    "FootstepsMaple": "仙子之径幻纹",
    "GaraAlternateSkin": "Gara 不朽外观",
    "GaussSentinelSkin": "阿尔特拉守护外观",
    "HoverboardStickerBaroB": "绿色Ki'teer 游猎K式悬浮板涂鸦",
    "JadeImmortalSkin": "Jade 不朽外观",
    "NecraArmorA": "熔铸肩甲",
    "NecraArmorC": "熔铸胸甲",
    "NecraArmorL": "熔铸膝甲",
    "SummerIgnisSkin": "伊格尼斯夏至外观",
    # ========== 杂项 ==========
    "BaroKiTeerDecorationG": "矽镁 乐升饰物",
    "CorpusRailjackLoginSongItem": "《航道星舰全面改造》登录音乐",
    "GlyphFactionCorpus": "CORPUS 浮印",
    "JavisExperimentsPosterC": "哈维光度涂鸦",
    "LisetPropCleaningDroneBaroPink": "内务 Ki'teer 无人机（薰衣草冰）",
    "LisetPropGrineerFlak": "高炮战机装饰",
    "MummyQuestKeyBlueprint": "Inaros之沙",
    "PhotoboothTileInarosTomb": "Inaros 古墓场景",
    "T4VoidProjectionPBronze": "后纪A2遗物",
    "TarotCardTennoConC": "火卫二迅敏节虫PREX卡牌",
    "TwinSnakesGlyph": "“秩序“-“混乱“浮印",
}

# 集团名称映射
SYNDICATE_NAMES = {
    # 六大集团（标准）
    "ArbitersSyndicate": "均衡仲裁者",
    "CephalonSudaSyndicate": "中枢苏达",
    "SteelMeridianSyndicate": "钢铁防线",
    "RedVeilSyndicate": "血色面纱",
    "NewLokaSyndicate": "新世间",
    "PerrinSyndicate": "佩兰数列",
    # 三大平原
    "CetusSyndicate": "希图斯（地球平原）",
    "SolarisSyndicate": "索拉里斯（金星平原）",
    "EntratiSyndicate": "英择谛（火卫二平原）",
    # 扎里曼号 962 4745 9509 17633 18886 20538 22142 22644 23797 26173 30598 30821 40777 47855 56217 56248 59696 62376 64659 71208 71237 74694 91320 95764 99343 99685 99718
    "ZarimanSyndicate": "扎里曼号",
    # 解剖圣所（英择谛实验室）
    "EntratiLabSyndicate": "解剖圣所",
    # 霍尼瓦尔
    "HexSyndicate": "霍尼瓦尔",
    # 福尔图娜子集团
    "VentKidsSyndicate": "Vent Kids",
    "VoxSyndicate": "Vox",
    # 其他子集团
    "QuillsSyndicate": "Quills",
    "NecraloidSyndicate": "Necraloid",
    "KahlSyndicate": "Kahl",
    "OstronSyndicate": "奥斯特",
    "SolarisUnitedSyndicate": "索拉里斯联合",
    "VoxSolarisSyndicate": "索拉里斯之声",
    "CavaleroSyndicate": "卡瓦莱罗",
    # 1999 日历/广播军团
    "RadioLegionSyndicate": "广播军团",
    "RadioLegionIntermissionSyndicate": "广播军团 - 章节间奏",
    "NightcapJournalSyndicate": "夜记",
    "EventSyndicate": "事件集团",
}

# 六集团（标准集团），用于分类展示
STANDARD_SYNDICATES = {
    "ArbitersSyndicate",
    "CephalonSudaSyndicate",
    "SteelMeridianSyndicate",
    "RedVeilSyndicate",
    "NewLokaSyndicate",
    "PerrinSyndicate",
}

# 三大平原
PLAINS_SYNDICATES = {
    "CetusSyndicate",
    "SolarisSyndicate",
    "EntratiSyndicate",
}

# 扎里曼号
ZARIMAN_SYNDICATES = {
    "ZarimanSyndicate",
}

# 解剖圣所
ENTRATI_LAB_SYNDICATES = {
    "EntratiLabSyndicate",
}

# 霍尼瓦尔
HEX_SYNDICATES = {
    "HexSyndicate",
}

# 1999 日历/广播军团（用于过滤或单独展示）
RADIO_LEGION_SYNDICATES = {tag for tag in SYNDICATE_NAMES if tag.startswith("RadioLegion")} | {"NightcapJournalSyndicate"}

# 赏金池
BOUNTY_POOL = [
    {
        "bountyid": "1",
        "title": "对空防御",
        "region": "EntratiLab", 
        "mission": "杀死3个飞行的低语者敌人", # T5
        "description": "当低语者从上空侵犯我们时，我们不会袖手旁观。干掉它们的空中部队。"
    },
    {
        "bountyid": "2",
        "title": "大人物",
        "region": "EntratiLab", 
        "mission": "消灭2名暴戾虚空锐将", # T1
        "description": "早该让那些不听话的暴戾虚空锐将看看到底是谁掌控这一地方。把他们大卸八块。"
    },
    {
        "bountyid": "3",
        "title": "化学课",
        "region": "EntratiLab", 
        "mission": "用硫酸泼向30名敌人", 
        "description": "实验时间！当硫酸与我们的敌人接触时会发生什么？我等着你们的结果。"
    },
    {
        "bountyid": "13",
        "title": "寂静无声",
        "region": "EntratiLab", 
        "mission": "消灭 200 名低语者敌人", # T4
        "description": "低语者越来越吵闹，我们需要安静才能集中注意力。去吧，让他们闭嘴。永久地。"
    },
    {
        "bountyid": "15",
        "title": "虚空狂潮",
        "region": "EntratiLab", 
        "mission": "激活1个虚空泉脉", # T2
        "description": "虚空泉脉不可避免地提醒我们，虚空已经渗入实验室。唯一的出路就是接受它们。"
    },
]
